{pkgs}: {
  deps = [
    pkgs.perlPackages.PodMarkdown
    pkgs.sbclPackages.parse-float
    pkgs.python312Packages.python-lsp-black
    pkgs.rocmPackages_6.tensile
    pkgs.haskellPackages.hsqml-demo-samples
    pkgs.haskellPackages.pokitdok
    pkgs.sbclPackages.cl-xkeysym
    pkgs.sbclPackages.floating-point-contractions
    pkgs.topicctl
    pkgs.python312Packages.moreorless
    pkgs.python311Packages.tldextract
    pkgs.haskellPackages.hvect
    pkgs.haskellPackages.conduit-zstd
    pkgs.python311Packages.ipyxact
    pkgs.rPackages.test3probe
    pkgs.rPackages.wiqid
    pkgs.rPackages.sleev
    pkgs.haskellPackages.string-variants
    pkgs.python312Packages.graphite-web
    pkgs.mini-calc
    pkgs.rPackages.hurricaneexposure
    pkgs.rPackages.IterativeHardThresholding
    pkgs.python312Packages.fabric
    pkgs.sbclPackages.doplus
    pkgs.luastatus
    pkgs.libretro.fbneo
    pkgs.swayidle
    pkgs.rPackages.rintrojs
  ];
}
